# Generated by Django 2.1 on 2018-08-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Ссылку', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
