# Generated by Django 2.1 on 2018-08-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20180812_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.TextField(default=0, max_length=500, verbose_name='Описание'),
        ),
    ]
