# Generated by Django 2.1 on 2018-08-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20180812_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='link',
            field=models.URLField(max_length=100, verbose_name='Ссылка'),
        ),
    ]
