# Generated by Django 2.1 on 2018-08-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_auto_20180812_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Описание'),
        ),
    ]
