# Generated by Django 2.1 on 2018-08-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20180812_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
