# Generated by Django 2.1 on 2018-08-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_auto_20180815_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='text',
        ),
    ]
