# Generated by Django 2.1 on 2018-08-16 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_auto_20180816_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
