# Generated by Django 2.1 on 2018-08-16 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_auto_20180816_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
