# Generated by Django 2.1 on 2018-08-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0011_auto_20180816_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='link',
            field=models.URLField(blank=True, max_length=100, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок'),
        ),
    ]
