# Generated by Django 2.1 on 2018-08-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0012_auto_20180816_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='link',
            field=models.URLField(blank=True, default='http://', max_length=300, verbose_name='Ссылка'),
        ),
    ]
